
name: Add-On
on:
  workflow_dispatch:
  schedule:
    # Run at 17 past the hour, every hour, Monday through Friday
    - cron:  "17 * * * 1-5"

jobs:
  Run-Add-On:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - uses: actions/cache@v2
        id: cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - run: python main.py
        env:
          DC_USERNAME: ${{ secrets.DC_USERNAME }}
          DC_PASSWORD: ${{ secrets.DC_PASSWORD }}
